name: Artificial Intelligence Agency
favicon: null
layout_spectrum: 0
typography_spectrum: 0.16956
title: Artificial Intelligence Agency
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-72833238-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#3d9299'
    - '#4dbcc5'
    - '#132f33'
    - '#91d4d5'
  brandStrength: 1
  lightness: 1
  saturation: 0
  rhythmicContrast: 1
purpose: []
